name: Check C/C++ Code

on: [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Linux Dependencies and Support Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential ninja-build cppcheck

      - name: Run cppcheck
        run: cppcheck --enable=all --suppress=styleunusedFunction,unreadVariable,uninitvar --inconclusive --quiet --error-exitcode=1 Core/Src/ Core/Inc/
